services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - DEMO_REDIS_ADDR=redis:6379
      - DEMO_APP_ADDR=:8000
    # Depends on redis to start correctly.
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
        - ./data:/data
    ports:
        - '6379:6379'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
