---
#   - Setup hostname of VM as `demo-ops`.
#   - Create a user `demo`.
#   - Harden the security:
#     - Disable root login.
#     - Setup a basic firewall (e.g., UFW) allowing only specific ports.
#   - Configure `sysctl` for sane defaults. (For eg: increasing open files limit)
#   - Configure sysctl for sane defaults. For each sysctl parameter changed:
#     - Document the change.
#     - Provide a brief justification or explanation (2-3 lines) detailing why this specific change was made and its implications.
#   - Set the system's timezone to "Asia/Kolkata".
#   - Install Docker and Docker-Compose.
#   - Configure Docker Daemon to have sane defaults. For eg: keep logs size in check.
#   - Deploy the `docker-compose.yml` in `/etc/demo-ops` and start the services.
#   - Install and configure monitoring tools like Prometheus and Grafana. Ensure app and redis metrics are being scraped.

- name: Configure VM for running application
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Setup hostname of Virtual Machine as demo-ops
      ansible.builtin.hostname:
        name: demo-ops

    - name: Create user named "demo"
      ansible.builtin.user:
        name: demo
        comment: Demo user
        group: admin

    - name: Disable root login
      user:
        name: root
        password_lock: true


